// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v5.26.0
// source: protocol/pb/dbservice_protofile/dbservice.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DB_PING_REQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int64 `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
}

func (x *DB_PING_REQ) Reset() {
	*x = DB_PING_REQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_pb_dbservice_protofile_dbservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DB_PING_REQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DB_PING_REQ) ProtoMessage() {}

func (x *DB_PING_REQ) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_pb_dbservice_protofile_dbservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DB_PING_REQ.ProtoReflect.Descriptor instead.
func (*DB_PING_REQ) Descriptor() ([]byte, []int) {
	return file_protocol_pb_dbservice_protofile_dbservice_proto_rawDescGZIP(), []int{0}
}

func (x *DB_PING_REQ) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type DB_PING_RESP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp int64 `protobuf:"varint,1,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
}

func (x *DB_PING_RESP) Reset() {
	*x = DB_PING_RESP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_pb_dbservice_protofile_dbservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DB_PING_RESP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DB_PING_RESP) ProtoMessage() {}

func (x *DB_PING_RESP) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_pb_dbservice_protofile_dbservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DB_PING_RESP.ProtoReflect.Descriptor instead.
func (*DB_PING_RESP) Descriptor() ([]byte, []int) {
	return file_protocol_pb_dbservice_protofile_dbservice_proto_rawDescGZIP(), []int{1}
}

func (x *DB_PING_RESP) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

// tick 值每次 +1 和时间戳形成双重校验
type DB_HEART_BEAT_REQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int64 `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"` // 时间戳
	Tick      int32 `protobuf:"varint,2,opt,name=Tick,proto3" json:"Tick,omitempty"`           // tick值
}

func (x *DB_HEART_BEAT_REQ) Reset() {
	*x = DB_HEART_BEAT_REQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_pb_dbservice_protofile_dbservice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DB_HEART_BEAT_REQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DB_HEART_BEAT_REQ) ProtoMessage() {}

func (x *DB_HEART_BEAT_REQ) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_pb_dbservice_protofile_dbservice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DB_HEART_BEAT_REQ.ProtoReflect.Descriptor instead.
func (*DB_HEART_BEAT_REQ) Descriptor() ([]byte, []int) {
	return file_protocol_pb_dbservice_protofile_dbservice_proto_rawDescGZIP(), []int{2}
}

func (x *DB_HEART_BEAT_REQ) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DB_HEART_BEAT_REQ) GetTick() int32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

type DB_HEART_BEAT_RESP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int64 `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"` // 时间戳
	Ticl      int32 `protobuf:"varint,2,opt,name=Ticl,proto3" json:"Ticl,omitempty"`           // tick值
}

func (x *DB_HEART_BEAT_RESP) Reset() {
	*x = DB_HEART_BEAT_RESP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_pb_dbservice_protofile_dbservice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DB_HEART_BEAT_RESP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DB_HEART_BEAT_RESP) ProtoMessage() {}

func (x *DB_HEART_BEAT_RESP) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_pb_dbservice_protofile_dbservice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DB_HEART_BEAT_RESP.ProtoReflect.Descriptor instead.
func (*DB_HEART_BEAT_RESP) Descriptor() ([]byte, []int) {
	return file_protocol_pb_dbservice_protofile_dbservice_proto_rawDescGZIP(), []int{3}
}

func (x *DB_HEART_BEAT_RESP) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DB_HEART_BEAT_RESP) GetTicl() int32 {
	if x != nil {
		return x.Ticl
	}
	return 0
}

var File_protocol_pb_dbservice_protofile_dbservice_proto protoreflect.FileDescriptor

var file_protocol_pb_dbservice_protofile_dbservice_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x64, 0x62,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x2f, 0x64, 0x62, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x2b, 0x0a, 0x0b, 0x44, 0x42, 0x5f, 0x50, 0x49, 0x4e, 0x47, 0x5f, 0x52, 0x45, 0x51,
	0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x2c,
	0x0a, 0x0c, 0x44, 0x42, 0x5f, 0x50, 0x49, 0x4e, 0x47, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x12, 0x1c,
	0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x45, 0x0a, 0x11,
	0x44, 0x42, 0x5f, 0x48, 0x45, 0x41, 0x52, 0x54, 0x5f, 0x42, 0x45, 0x41, 0x54, 0x5f, 0x52, 0x45,
	0x51, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x54, 0x69, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x54,
	0x69, 0x63, 0x6b, 0x22, 0x46, 0x0a, 0x12, 0x44, 0x42, 0x5f, 0x48, 0x45, 0x41, 0x52, 0x54, 0x5f,
	0x42, 0x45, 0x41, 0x54, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x63, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x54, 0x69, 0x63, 0x6c, 0x42, 0x07, 0x5a, 0x05, 0x2e,
	0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protocol_pb_dbservice_protofile_dbservice_proto_rawDescOnce sync.Once
	file_protocol_pb_dbservice_protofile_dbservice_proto_rawDescData = file_protocol_pb_dbservice_protofile_dbservice_proto_rawDesc
)

func file_protocol_pb_dbservice_protofile_dbservice_proto_rawDescGZIP() []byte {
	file_protocol_pb_dbservice_protofile_dbservice_proto_rawDescOnce.Do(func() {
		file_protocol_pb_dbservice_protofile_dbservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocol_pb_dbservice_protofile_dbservice_proto_rawDescData)
	})
	return file_protocol_pb_dbservice_protofile_dbservice_proto_rawDescData
}

var file_protocol_pb_dbservice_protofile_dbservice_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protocol_pb_dbservice_protofile_dbservice_proto_goTypes = []interface{}{
	(*DB_PING_REQ)(nil),        // 0: DB_PING_REQ
	(*DB_PING_RESP)(nil),       // 1: DB_PING_RESP
	(*DB_HEART_BEAT_REQ)(nil),  // 2: DB_HEART_BEAT_REQ
	(*DB_HEART_BEAT_RESP)(nil), // 3: DB_HEART_BEAT_RESP
}
var file_protocol_pb_dbservice_protofile_dbservice_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_pb_dbservice_protofile_dbservice_proto_init() }
func file_protocol_pb_dbservice_protofile_dbservice_proto_init() {
	if File_protocol_pb_dbservice_protofile_dbservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocol_pb_dbservice_protofile_dbservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DB_PING_REQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_pb_dbservice_protofile_dbservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DB_PING_RESP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_pb_dbservice_protofile_dbservice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DB_HEART_BEAT_REQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_pb_dbservice_protofile_dbservice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DB_HEART_BEAT_RESP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocol_pb_dbservice_protofile_dbservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_pb_dbservice_protofile_dbservice_proto_goTypes,
		DependencyIndexes: file_protocol_pb_dbservice_protofile_dbservice_proto_depIdxs,
		MessageInfos:      file_protocol_pb_dbservice_protofile_dbservice_proto_msgTypes,
	}.Build()
	File_protocol_pb_dbservice_protofile_dbservice_proto = out.File
	file_protocol_pb_dbservice_protofile_dbservice_proto_rawDesc = nil
	file_protocol_pb_dbservice_protofile_dbservice_proto_goTypes = nil
	file_protocol_pb_dbservice_protofile_dbservice_proto_depIdxs = nil
}
